# Generated by Django 4.2.25 on 2025-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
